### ISSUE TITLE
Please consider including some concurrent SLM survey, mobile-specific SLM designs and SLM-oriented hardware optimisation as candidates

### ISSUE THREAD

**Issue by caidongqi** [FairyFali/SLMs-Survey#3]
Dear authors,

Thank you for organising this comprehensive small language survey, I learned a lot from it. Here are some recent relevant works from our team, could you please consider including them in the next version to expand the related literature scope:

1. SLM Survey (https://arxiv.org/abs/2401.08092): another survey providing an overarching understanding of how current approaches are tackling the resource challenges on real mobile phones.
2. PhoneLM（https://arxiv.org/abs/2411.05046): an efficient, capable, and fully open-sourced small language family.
3. M4 (https://dl.acm.org/doi/10.1145/3636534.3649361): a mulitmodal mobile AI firmware.
4.  mllm-NPU (https://arxiv.org/pdf/2407.05858): a NPU acceleration system.

Thank you for consideration,
Best,
Dongqi
PhD student at BUPT

**Comment by caidongqi** [comment]
btw, there is a small typo in the README file:

LLMaaS: "Wangsong Yin". Piotr Nawrot et al. 2024. [[Paper](https://arxiv.org/abs/2403.11805)]

The right one shall be:
LLMaaS: "LLM as a System Service on Mobile Devices", Wangsong Yin et al. arXiv 2024. [[Paper](https://arxiv.org/abs/2403.11805)]

Please consider updating it when available.

Best,
Dongqi

**Comment by derrickmo** [comment]
Hi Dongqi,

Thanks for the feedback; we will certainly revisit the scope and look into future improvements. 
The typo is now fixed. We will continue to review the list and improve the references. 

Best,

**Comment by FairyFali** [comment]
> Dear authors,
> 
> Thank you for organising this comprehensive small language survey, I learned a lot from it. Here are some recent relevant works from our team, could you please consider including them in the next version to expand the related literature scope:
> 
> 1. SLM Survey (https://arxiv.org/abs/2401.08092): another survey providing an overarching understanding of how current approaches are tackling the resource challenges on real mobile phones.
> 2. PhoneLM（https://arxiv.org/abs/2411.05046): an efficient, capable, and fully open-sourced small language family.
> 3. M4 (https://dl.acm.org/doi/10.1145/3636534.3649361): a mulitmodal mobile AI firmware.
> 4. mllm-NPU (https://arxiv.org/pdf/2407.05858): a NPU acceleration system.
> 
> Thank you for consideration, Best, Dongqi PhD student at BUPT

Thanks for your contribution, we have marked your work and will consider to add them in the next version. 

Best, 
Fali
