### ISSUE TITLE
Follow up on EMNLP 2024 Meeting

### ISSUE THREAD

**Issue by gyuhwung-cho** [FairyFali/SLMs-Survey#4]
Dear Mr Wang (@FairyFali )

My name is Gyu-Hwung Cho from Naver Corporation
It was a pleasure meeting you at the EMNLP 2024 conference.

I wanted to express my gratitude for your valuable questions and the interest you showed in our paper titled "**SLM as Guardian: Pioneering AI Safety with Small Language Models**" during the poster session.

This link leads to our paper. (https://aclanthology.org/2024.emnlp-industry.99.pdf)

if you have any question, please contact me at **gyuhwung.cho@navercorp.com**

Once again, thank you for showing interest in our poster. I hope you a nice day.

Sincerely,
Gyu-Hwung Cho

**Comment by FairyFali** [comment]
Happy to shortly meet you at the conference as well. We have marked your paper and will include it in the next version. 

Thanks,
Fali
